language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.24.1
script:
  - rustc --version
  - cargo build
  - cargo test
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] || [ "$TRAVIS_RUST_VERSION" == "beta" ]; then
      cd ci-tests;
      cargo test;
    fi
