language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.24.1
script:
  - rustc --version
  - (rustc --version | grep nightly && echo "nightly build!") || touch not_nightly
  - cargo build
  - cargo test
  - if [ ! -f not_nightly ]; then cargo test --features no_core; fi
